### PR TITLE
Picocli 3.9.1

### PR DESCRIPTION
**Pull request by colinkuo**
1. Upgrade to picocli 3.9.1 and spring boot 2.0.7.RELEASE
2. Allow single MainCommand to be loaded by Spring. Otherwise, throw the exception
3. Fix test case of Nested commands

### CODE REVIEW

**Comment by kakawait** [comment]
@colinkuo thank you for that huge PR. I'm a bit busy this week. I'll check that next week.

**Comment by kakawait** [comment]
@colinkuo that sound good. I'll just polish something and checkout why travis is failing. Then I'll merge it.

Thank for that huge contribution.

**Comment by can-can** [comment]
Hi, Do you have time to publish new release version? If you need any help, I'd like to give you a hand.

**Comment by kakawait** [comment]
Sorry guys I was totaly busy + some personal stuff drained my time. I'll plan that MR that next week

**Comment by kakawait** [comment]
@colinkuo Thank you I'll merge it on branch `1.0.0-beta-1` that I'll merge to master as soon I polished other things

**Pull request merged**
